version: "3"

services:
  apollo-proxy:
    build: 
      context: ./apollo-server
    image: rmarechal/svelte-neo4j-graphql-apollo-server
    ports:
      - "4000:4000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687

  neo4j:
    image: neo4j:5.23.0
    # # In case of user error due to undefined $UID and $GID, run the following command:
    # # UID=$(id -u) GID=$(id -g) docker compose up
    # user: '${UID}:${GID}' 
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "apoc-extended", "graph-data-science"]
    ports:
      - "7474:7474"
      - "7687:7687"

  # Grafana Alloy batches and processes traces sent to it, generating
  # auto-logs from those traces.
  # Includes Metrics, Logs, Traces and Profiles.
  alloy:
    image: grafana/alloy:v1.3.1
    network_mode: host
    ports:
      - "12345:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - "./neo4j-data-importer/alloy/config.alloy:/etc/alloy/config.alloy"
      - "./neo4j-data-importer/alloy/endpoints.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]