version: "3"

services:
  apollo-proxy:
    build: 
      context: ./apollo-server
    image: rmarechal/svelte-neo4j-graphql-apollo-server
    ports:
      - "4000:4000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687

  neo4j:
    image: neo4j:5.23.0
    # # In case of user error due to undefined $UID and $GID, run the following command:
    # # UID=$(id -u) GID=$(id -g) docker compose up
    # user: '${UID}:${GID}' 
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "apoc-extended", "graph-data-science"]
    ports:
      - "7474:7474"
      - "7687:7687"
